redis:
    address: redis:6379
    password: ${REDIS_PASSWORD}
livekit:
    api_key: ${LIVEKIT_API_KEY}
    api_secret: ${LIVEKIT_API_SECRET}
    ws_url: ws://livekit:7880
rtmp:
    port: 1935
whip:
    port: 8081 # Переназначен с 8080
webhook_url: http://host.docker.internal:3000/webhook/livekit # NestJS на localhost:3000
